AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageName:
    Type: String
  ImageTag:
    Type: String

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}:${ImageTag}
      PackageType: Image
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId:
              Ref: ApiGatewayApi
